"""Re-export from shared package — keeps all existing imports working."""
from shared.contracts import *  # noqa: F401, F403
from shared.contracts import (  # noqa: F401 — explicit re-exports for type checkers
    SCHEMA_VERSION as SCHEMA_VERSION,
    Articulation as Articulation,
    Difficulty as Difficulty,
    DynamicMarking as DynamicMarking,
    EngravedOutput as EngravedOutput,
    EngravedScoreData as EngravedScoreData,
    ExpressionMap as ExpressionMap,
    ExpressiveNote as ExpressiveNote,
    HarmonicAnalysis as HarmonicAnalysis,
    HumanizedPerformance as HumanizedPerformance,
    InputBundle as InputBundle,
    InputMetadata as InputMetadata,
    InstrumentRole as InstrumentRole,
    MidiTrack as MidiTrack,
    Note as Note,
    OrchestratorCommand as OrchestratorCommand,
    PedalEvent as PedalEvent,
    PianoScore as PianoScore,
    PipelineConfig as PipelineConfig,
    PipelineVariant as PipelineVariant,
    QualitySignal as QualitySignal,
    RealtimeChordEvent as RealtimeChordEvent,
    RemoteAudioFile as RemoteAudioFile,
    RemoteMidiFile as RemoteMidiFile,
    ScoreChordEvent as ScoreChordEvent,
    ScoreMetadata as ScoreMetadata,
    ScoreNote as ScoreNote,
    ScoreSection as ScoreSection,
    Section as Section,
    SectionLabel as SectionLabel,
    TempoChange as TempoChange,
    TempoMapEntry as TempoMapEntry,
    TranscriptionResult as TranscriptionResult,
    WorkerResponse as WorkerResponse,
    beat_to_sec as beat_to_sec,
    sec_to_beat as sec_to_beat,
)
